# Generated by Django 3.0.8 on 2020-07-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0005_auto_20200711_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
