# Generated by Django 3.0.3 on 2020-07-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelApp', '0009_hotel_avgreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='AvgReview',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
